config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'help' => 'pages#help'
  get 'about' => 'pages#about'
  get 'services' => 'pages#services'
  
  resources :appointment_requests, only: [:new, :create]

end

app/models/appointment_request.rb
class AppointmentRequest < ActiveRecord::Base
  validates_presence_of :first_name, :last_name, :email, :comments
  
  validates_format_of(
    :email,
    with: /\A[\w.]+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}\Z/,
    message: 'Not a valid email'
  )
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointment_requests_controller.rb
class AppointmentRequestsController < ApplicationController
  def new
    @appointment_request = AppointmentRequest.new
  end
  def create
    @appointment_request = AppointmentRequest.new(appointment_request_params)
    # binding.pry
    
    if @appointment_request.valid?
      AppointmentRequestMailer.appointment_request_confirmation_email(@appointment_request).deliver
        
      AppointmentRequestMailer.appointment_request_internal_email(@appointment_request).deliver
        
      redirect_to root_url, :notice =>"Thank you for reaching out. We'll be in touch with you soon"
    else
      # re-render new form (this automatically displays errors)
      render action: 'new'
    end
      
    
    
    # begin
      
    # rescue Exception => e
    #   puts e.message
    # end
    
    # if result1 and result2 
    #   message = 'Thanks, check your email'
    # else 
    #   message = 'Email did not send'
    # end
    
    
  end
    #need so
    
    #   if @appointment_request.deliver
    #      flash[:notice] = 'Thank you for your message. We will contact you soon!'
    #      flash[:color]= "valid"
    #   else
    #      flash[:notice] = 'Cannot send message.'
    #      flash[:color]= "invalid"
    #   end     
    #      render :new
  
  private
  
  def appointment_request_params
    params.require(:appointment_request).permit(:first_name, :last_name, :sex, :email, :phone, :comments, :type_of_appointment)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def appointment
  end
  def about
  end
  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/appointment_requests/new.html.erb
<% provide :container_class, "container-no-bg" %>

<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6 white-bg">
  <h2>Welcome! Please fill out the fields below.</h2>
    <hr>
    <%= simple_form_for @appointment_request, wrapper: :horizontal_form, html: {class: 'p-v'} do |f| %>
      <%= f.input :first_name, label: 'First name' %>
      <%= f.input :last_name %>
      <%= f.input :sex, :collection => ['Female', 'Male', 'Other'], label: 'Gender' %>
      <%= f.input :email, label: 'Email', placeholder: 'We never send spam or newsletters'  %>
      <%= f.input :phone, inline_label: 'Phone', placeholder: 'XXX-XXX-XXXX' %>
      <%= f.input :comments, placeholder: 'Tell us why you are here' %>
      <%= f.input :type_of_appointment, :collection => ['Professional help', 'Someone to talk to', 'Advocacy', 'Unsure'] %>
      <%= f.error :base %>
      
      <hr>
      
      <div class="text-center">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
      
    <% end %>
  </div>
  <div class="col-sm-3"></div>
</div>

app/views/layouts/_flashes.html.erb
<% if flash[:notice].present? %>
  <div class="alert-success"><%= flash[:notice] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Community Cares</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <header class="navbar navbar-default navbar-inverse">
        <nav>
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "About Us",  about_path %></li>
            <li><%= link_to "Our Services", services_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Request an Appointment",  new_appointment_request_path  %></li>
          </ul>
        </nav>
    </header>

    <div class="container <%= yield :container_class %>">
      <%= render 'layouts/flashes' %>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/pages/about.html.erb
<html>
  <head>
    <div style="background-color:lightsteelblue"></div>
    <div class="center jumbotron" style="background-color:aliceblue">
      <h1>+About Us<br><br></h1>
    </head>
  <body>
    <p>Community Cares is community-based and peer-led. Representatives of Community Cares 
    belong to all corners of the university and may be of any age, gender or background--what 
    recruits people to our mission is empathy. We have either "been there" personally or 
    witnessed a loved one's crisis unfold, and we recognize that mental health is not just 
    a concern for those with a diagnosable mental illness. We are not equipped nor intended 
    to offer professional care, rather, we guarantee our empathy, non-judgement, emotional 
    support and shoulder-to-shoulder advocacy.</p>
    
    <h2>+Who We Serve</h2>
    <p>One in four young adults ages 18-24 has a diagnosable mental illness and 
    though over 70% of students living with a mental condition experience a mental 
    health crisis on campus, at least 34% report that their college did not know 
    about their crisis. Suicide is the third leading cause of death on college 
    campuses. More than 80 percent of college students felt overwhelmed by all 
    they had to do in the past year and 45 percent have felt things were hopeless. 
    These crisis are not self-contained, and students need meaningful short and 
    long-term support networks to rely on and feel comfortable approaching.
    </p>
    
    <h2>+Join Us</h2>
    <p>If you are interested in becoming involved with Community Cares, you can't! 
    because we don't exist yet.
    </p>
    
    <div class="panel">
      <div class="panel-heading">+News and Information</div>
      <div class="panel-body"></div>
      <!-- List group -->
        <ul class="list-group">
          <li class="list-group-item"><a href="http://www.bestcolleges.com/resources/top-5-mental-health-problems-facing-college-students/">
          Top 5 Mental Health Problems Facing College Students</a></li>
          <li class="list-group-item"><a href="http://www.newuniversity.org/2015/04/opinion/college-stresses-render-need-for-mental-health-resources-on-campus/">
          College Stresses Render Need For Mental Health Resources on Campus</a></li>
          <li class="list-group-item"><a href="http://dailyorange.com/2015/03/diaz-campus-mental-health-services-lack-proper-promotion-accessibility/">
          Campus Mental Health Services Lack Proper Promotion and Accessibility</a></li>
          <li class="list-group-item"><a href="https://www.psychologytoday.com/blog/theory-knowledge/201402/the-college-student-mental-health-crisis">
          The College Student Mental Health Crisis</a></li>
          <li class="list-group-item"><a href="http://www.apa.org/about/gr/education/news/2011/college-campuses.aspx">
          The State of Mental Health on College Campuses: A Growing Crisis</a></li>
          <li class="list-group-item"><a href="http://www2.nami.org/Content/NavigationMenu/Find_Support/NAMI_on_Campus1/Learn_About_The_Issue/Learn_About_The_Issue.htm">
          NAMI: Facts about Mental Health on College Campuses</a></li>
    </ul>
  </div>
    
  </body>
  </div>
</html>

app/views/pages/help.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Community Cares Help Page</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    We are here to help you!  This page is here to help you navigate our website!<br>
    Contact: 
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% provide :container_class, "container-no-bg" %> 
<div class="center">

<h1>COMMUNITY CARES</h1>

<h2>
This is The Place If You Need Help 
</h2>  

</div>

<div class="center">
<%= image_tag("communitycares.png", alt: "We Care") %>
</div>

app/views/pages/services.html.erb
<html>
  <head>
    <div style="background-color:lightsteelblue"></div>
    <div class="center jumbotron" style="background-color:aliceblue">
      <h1>Who We Serve<br><br></h1>
    </head>
  <body>
    <p>One in four young adults aged 18-24 has a diagonsable mental illness and though over 70% of students living with a mental 
    conition experience a mental health crisis on campus, at least 34% report that their college did not know about their crisis.  
    Suicide is the third leading cause of death on college campuses.  More than 80% of college students felt overwhelmed by all 
    they had to do in the past year and 45% have felt things were hopeless.  These crises are not self-contained, and students 
    need meaningful short and long-term support networks to rely on and feel comfortable approaching.  
  </body>
  </div>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>